[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["bark", "mirror"]

[project]
name = "ruff-pre-commit"
version = "0.0.2"
dependencies = [
    "ruff==0.14.8",
]
